[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.yapf]
based_on_style = "facebook"
blank_line_before_nested_class_or_def = true
split_all_top_level_comma_separated_values = true
